# Generated by Django 4.0.3 on 2022-04-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='ISWC',
            field=models.CharField(db_index=True, help_text='International Standard Musical Work Code', max_length=250, unique=True, verbose_name='International Standard Musical Work Code'),
        ),
    ]
