# Generated by Django 4.0.3 on 2022-04-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicalapp', '0002_alter_work_iswc'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Musical Work Title', max_length=300, verbose_name='Musical Work Title')),
                ('ISWC', models.CharField(db_index=True, help_text='International Standard Musical Work Code', max_length=250, unique=True, verbose_name='International Standard Musical Work Code')),
            ],
            options={
                'verbose_name_plural': 'MusicalWorks',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='contributor',
            name='name',
            field=models.CharField(help_text='Contributor Name', max_length=300, unique=True, verbose_name='Contributor Name'),
        ),
        migrations.DeleteModel(
            name='Work',
        ),
        migrations.AddField(
            model_name='musicalwork',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributors', to='musicalapp.contributor'),
        ),
    ]
